'use client'
import React, { useEffect, useState } from 'react'
import {db} from '/configs/db'
import {CourseList} from '/configs/schema'
import CourseCard from '../_components/CourseCard'
import {Button} from '../../../components/ui/button'
function Explore() {
  const [courseList,setCourseList]=useState([]);
  const [pageIndex,setPageIndex]=useState(0);
  useEffect(()=>{
    GetAllCourse();
  },[pageIndex])
  const GetAllCourse=async()=>{
    const result=await db.select().from(CourseList).limit(9).offset(pageIndex*9);
    console.log(result);
    setCourseList(result)
    
  }
  return (
    <div><h2 className='text-white font-bold text-3xl'>Explore More Courses</h2>
    <p className='text-gray-600'>Explore more Courses generated by other uers</p>
    <div className='grid grid-cols-2 lg:grid-cols-3 gap-5'>{courseList?.map((course,index)=>(
      <div key={index}>
        <CourseCard course={course} />
      </div>
    ))}</div>
    <div className='flex justify-between mt-5'>
{pageIndex!=0 &&<Button onClick={()=>setPageIndex(pageIndex-1)}>Previous Page</Button>
}    <Button onClick={()=>setPageIndex(pageIndex+1)}>Next Page</Button>
    </div>
    </div>
  )
}

export default Explore