import {Permanent_Marker,Outfit} from "next/font/google";
import "./globals.css";
import {ClerkProvider} from '@clerk/nextjs'
import { shadesOfPurple } from "@clerk/themes";

const inter=Permanent_Marker

({subsets:["latin"],
  weight: '400',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: shadesOfPurple,
    }}

    >
    <html lang="en">
      <body
        className={inter.className}>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
